name: commerce-demo
recipe: drupal8
config:
  webroot: web
services:
  appserver:
    webroot: web
    xdebug: off
    config:
      php: .lando/php.ini
tooling:
  test:
    service: appserver
    cmd: "cp /app/web/core/phpunit.xml.dist /app/phpunit.xml && php /app/vendor/bin/phpunit -c /app/phpunit.xml"
