name: commerce-demo
recipe: drupal10
config:
  webroot: web
env_file:
  - defaults.env
  - .env
services:
  appserver:
    type: php:8.1
    composer_version: 2-latest
    webroot: web
    config:
      php: .lando/php.ini
    environment:
      DRUSH_OPTIONS_URI: https://commerce-demo.lndo.site
  chrome:
    type: compose
    services:
      image: zenika/alpine-chrome
      ports:
        - '9222'
      command: "chromium-browser --disable-gpu --headless --disable-dev-shm-usage --remote-debugging-address=0.0.0.0 --remote-debugging-port=9222 --no-sandbox --no-web-security --window-size=1080,1920 </dev/null"
      environment:
        SITE_URL: https://commerce-demo.lndo.site
        NODE_EXTRA_CA_CERTS: /user/.lando/certs/lndo.site.pem
  mailhog:
    # https://docs.lando.dev/config/mailhog.html#configuration
    type: mailhog
tooling:
  behat:
    service: appserver
    description: Run Behat
    cmd: /app/vendor/bin/behat -c /app/tests/behat/behat.yml
  phpunit:
    service: appserver
    cmd: "cp /app/web/core/phpunit.xml.dist /app/phpunit.xml && php /app/vendor/bin/phpunit -c /app/phpunit.xml"
  site-install:
    service: appserver
    cmd:
      - cmp --silent config/settings.local.php web/sites/default/settings.local.php || ( echo "web/sites/default/settings.local.php does not match config/settings.local.php, update?" && cp -iv config/settings.local.php web/sites/default/ )
      - drush site-install --no-interaction commerce_kickstart
      - drush -y pm:enable commerce_dps commerce_demo
      - drush -y config:import --partial --source=../config/splits/ci
      - drush -y config:import --partial --source=../config/splits/commerce_dps
      - drush uli
